// ALERT ACTIONS
export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// Register ACTIONS
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

// Login ACTIONS
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

// Update User ACTIONS
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

// Logout ACTIONS
export const LOGOUT_USER = "LOGOUT_USER";

// SideBar ACTIONS
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

// Handle Change ACTIONS
export const HANDLE_CHANGE = "HANDLE_CHANGE";

// Clear Form ACTIONS
export const CLEAR_VALUES = "CLEAR_VALUES";

// Create Job ACTIONS
export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

// Get Jobs ACTIONS
export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

// SetEdit Job ACTIONS
export const SET_EDIT_JOB = "SET_EDIT_JOB";

// Delete Job ACTIONS
export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";
export const DELETE_JOB_ERROR = "DELETE_JOB_ERROR";

// Edit Job ACTIONS
export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

// Show Stats ACTIONS
export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

// Clear Filters ACTIONS 
export const CLEAR_FILTERS = "CLEAR_FILTERS"

// Change Page ACTIONS
export const CHANGE_PAGE = "CHANGE_PAGE";
